# Imports

In [4]:
import numpy as np
import itertools

# Create Compatability Matrix

In [5]:
def generate_random_compatibility_matrix(num_clusters_method_a, num_clusters_method_b, constant_sum):
    random_matrix = np.zeros((num_clusters_method_a, num_clusters_method_b), dtype=int)
    cluster_a_list = np.zeros((num_clusters_method_a), dtype=int)

    for row_index in range(constant_sum):
        random_index = np.random.randint(0, num_clusters_method_a)
        cluster_a_list[random_index] += 1
    print("Cluster A sizes: ", cluster_a_list)

    for row_index in range(num_clusters_method_a):
        for _ in range(cluster_a_list[row_index]):
            random_index = np.random.randint(0, num_clusters_method_b)
            random_matrix[row_index, random_index] += 1

    return random_matrix


num_clusters_method_a = 4
num_clusters_method_b = 4
total_members = 100

compatibility_matrix = generate_random_compatibility_matrix(num_clusters_method_a, num_clusters_method_b, total_members)

print("Compatibility Matrix:\n", compatibility_matrix)


Cluster A sizes:  [30 29 19 22]
Compatibility Matrix:
 [[ 4  4  8 14]
 [ 5 12  8  4]
 [ 3  4  4  8]
 [ 7  8  2  5]]


# Brute Force Matching

In [14]:
def brute_force_matching(matrix):
    num_clusters_a = matrix.shape[0]

    all_permutations = list(itertools.permutations(range(num_clusters_a)))

    best_matching = None
    best_matching_sum = 0

    for permutation in all_permutations:
        matching_sum = np.sum(matrix[np.arange(num_clusters_a), permutation])
        if matching_sum > best_matching_sum:
            best_matching_sum = matching_sum
            best_matching = permutation

    return best_matching, best_matching_sum

In [12]:
# all_permutations = list(itertools.permutations(range(4)))
# print(all_permutations)
# print(np.sum(compatibility_matrix[np.arange(num_clusters_method_a), all_permutations[4]]))

[(0, 1, 2, 3), (0, 1, 3, 2), (0, 2, 1, 3), (0, 2, 3, 1), (0, 3, 1, 2), (0, 3, 2, 1), (1, 0, 2, 3), (1, 0, 3, 2), (1, 2, 0, 3), (1, 2, 3, 0), (1, 3, 0, 2), (1, 3, 2, 0), (2, 0, 1, 3), (2, 0, 3, 1), (2, 1, 0, 3), (2, 1, 3, 0), (2, 3, 0, 1), (2, 3, 1, 0), (3, 0, 1, 2), (3, 0, 2, 1), (3, 1, 0, 2), (3, 1, 2, 0), (3, 2, 0, 1), (3, 2, 1, 0)]
14


In [17]:
best_matching, best_matching_sum = brute_force_matching(compatibility_matrix)
print("Best Matching: ", best_matching)
print("Best Matching Sum: ", best_matching_sum)

Best Matching:  (3, 1, 2, 0)
Best Matching Sum:  37
